create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null default 'customer' check (role in ('customer', 'admin')),
  created_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(10, 2) not null check (price >= 0),
  discount numeric(5, 2) not null default 0 check (discount >= 0 and discount <= 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.products enable row level security;

revoke all on table public.profiles, public.products from anon, authenticated;
grant select, insert on table public.profiles to authenticated;
grant select on table public.products to anon, authenticated;
grant update, insert, delete on table public.products to authenticated;

create policy "Customers can create their own profile"
  on public.profiles for insert to authenticated
  with check ((select auth.uid()) = id);

create policy "Users can read their own profile"
  on public.profiles for select to authenticated
  using ((select auth.uid()) = id);

create policy "Anyone can read products"
  on public.products for select to anon, authenticated
  using (true);

create policy "Admins can manage products"
  on public.products for all to authenticated
  using (exists (
    select 1 from public.profiles
    where profiles.id = (select auth.uid()) and profiles.role = 'admin'
  ))
  with check (exists (
    select 1 from public.profiles
    where profiles.id = (select auth.uid()) and profiles.role = 'admin'
  ));

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''));
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

insert into public.products (name, price, discount)
values
  ('Orbita tee', 48, 0),
  ('Nebula hoodie', 96, 10),
  ('Eclipse cargo', 112, 15);
